# Generated by Django 5.2 on 2025-04-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='carbon_footprint',
            field=models.FloatField(default=0.0),
        ),
    ]
