// src/pages/searchpageStyles.js

const styles = {
  wrapper: {
    display: "flex",
    flexDirection: "column",
    minHeight: "100vh",
    width: "100vw",
    padding: "0",
    backgroundColor: "#f0f8f5",
    boxSizing: "border-box",
    margin: "0",
    animation: "fadeIn 0.8s ease-in",
    position: "relative",
    overflow: "hidden",
  },

  // Particle container
  particlesContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    pointerEvents: "none",
    overflow: "hidden",
    zIndex: 0,
  },

  particle: {
    position: "absolute",
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#a0d9a0",
    opacity: 0.8,
    animation: "fall 4s linear infinite",
  },

  tabList: {
    display: "flex",
    margin: "20px 10px",
    border: "1px solid #c5dacd",
    borderRadius: "10px",
    overflow: "hidden",
    backgroundColor: "#e6f4ec",
    width: "calc(100% - 20px)",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.05)",
    zIndex: 1,
  },
  tabButton: {
    flex: 1,
    padding: "12px 0",
    backgroundColor: "#e6f4ec",
    border: "none",
    fontSize: "16px",
    color: "#3d5943",
    cursor: "pointer",
    transition: "all 0.3s ease",
    fontWeight: "500",
  },
  activeTab: {
    backgroundColor: "#cfe8d7",
    color: "#1d3b29",
    fontWeight: "bold",
    borderBottom: "2px solid #5fa86f",
    transform: "scale(1.05)",
  },
  inputWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    margin: "18px 10px",
    width: "calc(100% - 20px)",
    zIndex: 1,
  },
  input: {
    width: "100%",
    padding: "14px 48px 14px 14px",
    borderRadius: "10px",
    border: "1px solid #b7d2bd",
    fontSize: "16px",
    outline: "none",
    backgroundColor: "#f8fbf9",
    boxSizing: "border-box",
    transition: "box-shadow 0.3s ease",
  },
  searchButton: {
    position: "absolute",
    right: "10px",
    background: "#5fa86f",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    padding: "8px 12px",
    cursor: "pointer",
    fontSize: "16px",
    transition: "background 0.3s ease, transform 0.2s ease",
    zIndex: 1,
  },
  searchButtonHover: {
    background: "#4d9360",
    transform: "scale(1.05)",
  },
  loadingText: {
    marginTop: "16px",
    fontSize: "14px",
    color: "#666",
    textAlign: "center",
    fontStyle: "italic",
    animation: "pulse 1.5s infinite",
    zIndex: 1,
  },
  resultsContainer: {
    margin: "20px 10px",
    width: "calc(100% - 20px)",
    flexGrow: 1,
    animation: "fadeIn 0.5s ease-in-out",
    zIndex: 1,
  },
  resultCard: {
    backgroundColor: "#f1f8f3",
    borderRadius: "10px",
    padding: "14px 18px",
    marginBottom: "14px",
    boxShadow: "0 2px 6px rgba(0,0,0,0.06)",
    border: "1px solid #d3e7d6",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    transition: "transform 0.3s ease",
    zIndex: 1,
  },
  resultCardHover: {
    transform: "translateY(-3px)",
    boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
  },
  resultName: {
    fontSize: "17px",
    fontWeight: "bold",
    margin: "0 0 4px",
    color: "#2f4936",
  },
  resultEmail: {
    fontSize: "14px",
    margin: "0 0 8px",
    color: "#4f6d58",
  },
  noResults: {
    textAlign: "center",
    color: "#889c91",
    fontSize: "15px",
    marginTop: "14px",
    fontStyle: "italic",
  },
  viewButton: {
    backgroundColor: "#00a86b",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    padding: "6px 14px",
    cursor: "pointer",
    fontSize: "14px",
    transition: "all 0.3s ease",
  },
  viewButtonHover: {
    backgroundColor: "#007a54",
    transform: "scale(1.05)",
  },
  resultImage: {
    maxWidth: "100px",
    height: "auto",
    marginBottom: "8px",
    borderRadius: "6px",
    transition: "transform 0.3s ease",
  },

  // Animations keyframes
  "@keyframes fadeIn": {
    from: { opacity: 0 },
    to: { opacity: 1 },
  },
  "@keyframes pulse": {
    "0%": { opacity: 1 },
    "50%": { opacity: 0.5 },
    "100%": { opacity: 1 },
  },
  "@keyframes fall": {
    "0%": { transform: "translateY(-20px)", opacity: 0 },
    "100%": { transform: "translateY(100vh)", opacity: 0 },
  },
};

export default styles;